apiVersion: v1
kind: Service
metadata:
  name: ps-app-service
  labels:
    group: app
spec:
  selector:
    app: ps-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
